apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  data: AgBjW29dSNeD1pX5mMkr/5IJmbBi2UDUFWi7qXSknpSiZzzaCzKSAZUVXjhe0ssihVEMb9sBs9waKfxloTGMOPcu5P1L1HpqT/b66y+AL+InfLTuf6GniCGlYEP6CX6jzRKx6MTEqiuzKi/OrSjhiYd1kTzys7jB4P9U2UjosHxeh22GKuqDpY5PY1t8qK0uyoSwZD8oNIATwo92wz8/Euj0GRsIDpbykmkucS4tY0GWucNUhQOxg1kgK+YPIULFwRNgay1PF29PgOk5GriaoFh21IoHxJglb/N+pkmrEnU6E4tBNh02rWzwjrNweGUGWfcSFKWO25BhFVf/OjgyQqITnX7icnnz96tzJd2hYDkYJth27Q9uEMHZ1flESdDpWB/b97S4PL1fn862mpPdEs8PSJCkc/QHx2PZJD4ocI8q7mnnlT+xELhHmHr/gFAJkxTPXZubTXvzSRJHcnXXEXmBgl52S++O0AxcyO9g8NyxcNMsxya7xzxZAFQcj2TDMzKYe5T34UahKeqtehmuoqNZLc2mUYV1SjAvRmCLbRiHjlO/K8zX18dWU4UBq410on72GtjdYyybKXtYyCZ/8iyoobdK4HphN3aV3Om+ij/0YsF2bOntugiTQmNqc/Y8ccH1KspjlDHY7Nip4eD54Wp8YcRQREseTReX6WpFHpbkYVYwLAHRi2hokj8fAv3eEZpX69uOOVeZTBlZQcO0xaYIY/Ao4PVSQef8Z5pMMZWmcmed/QkCGnvRGOEAEr5/xOoxc4hc+xCFcduMfqKJurJcK96dXWhaSFhyDBtWJLVYb/kxikXtVPegVSlJcPJL+oggv8PINrxa/ujyL0D8S/+y1dtLRPRDpwJVc5gtmUsONwUS41sRQ2VWsu2RZE6Gcvr1rRZJ8RqJtmuIYTiUSCCPog==

