apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mssql-server-linux
  namespace: dev
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: mssql-server-linux
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mssql-linux
    version: 0.7.0
  values:
    image:
      repository: microsoft/mssql-server-linux
      tag: latest
    acceptEula.value: Y
